AllCops:
  Exclude:
    - 'bin/*'
  NewCops: enable
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - 'config/**/*'
Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
    - 'app/models/ability.rb'
    - 'app/admin/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
    - 'app/models/ability.rb'
