# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DB_HODT']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>

development:
  <<: *default
  database: movies_development
  
test:
  <<: *default
  database: movies_test

production:
  <<: *default
  database: movies_production
  # username: movies
  # password: <%= ENV["MOVIES_DATABASE_PASSWORD"] %>
